# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anchor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anchor.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61nchor.proto\"\x80\x01\n\x06Object\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.Object.ObjectType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\x05\"5\n\nObjectType\x12\n\n\x06\x43OMMIT\x10\x00\x12\x08\n\x04TREE\x10\x01\x12\x08\n\x04\x42LOB\x10\x02\x12\x07\n\x03TAG\x10\x03\"}\n\x06\x41nchor\x12%\n\x07objects\x18\x01 \x03(\x0b\x32\x14.Anchor.ObjectsEntry\x12\x13\n\x0bprev_anchor\x18\x02 \x01(\t\x1a\x37\n\x0cObjectsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Object:\x02\x38\x01\x62\x06proto3')
)



_OBJECT_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='Object.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOB', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAG', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=92,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_OBJECT_OBJECTTYPE)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Object.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Object.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='Object.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBJECT_OBJECTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=145,
)


_ANCHOR_OBJECTSENTRY = _descriptor.Descriptor(
  name='ObjectsEntry',
  full_name='Anchor.ObjectsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Anchor.ObjectsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Anchor.ObjectsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=272,
)

_ANCHOR = _descriptor.Descriptor(
  name='Anchor',
  full_name='Anchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='Anchor.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prev_anchor', full_name='Anchor.prev_anchor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ANCHOR_OBJECTSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=272,
)

_OBJECT.fields_by_name['type'].enum_type = _OBJECT_OBJECTTYPE
_OBJECT_OBJECTTYPE.containing_type = _OBJECT
_ANCHOR_OBJECTSENTRY.fields_by_name['value'].message_type = _OBJECT
_ANCHOR_OBJECTSENTRY.containing_type = _ANCHOR
_ANCHOR.fields_by_name['objects'].message_type = _ANCHOR_OBJECTSENTRY
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Anchor'] = _ANCHOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'anchor_pb2'
  # @@protoc_insertion_point(class_scope:Object)
  ))
_sym_db.RegisterMessage(Object)

Anchor = _reflection.GeneratedProtocolMessageType('Anchor', (_message.Message,), dict(

  ObjectsEntry = _reflection.GeneratedProtocolMessageType('ObjectsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ANCHOR_OBJECTSENTRY,
    __module__ = 'anchor_pb2'
    # @@protoc_insertion_point(class_scope:Anchor.ObjectsEntry)
    ))
  ,
  DESCRIPTOR = _ANCHOR,
  __module__ = 'anchor_pb2'
  # @@protoc_insertion_point(class_scope:Anchor)
  ))
_sym_db.RegisterMessage(Anchor)
_sym_db.RegisterMessage(Anchor.ObjectsEntry)


_ANCHOR_OBJECTSENTRY.has_options = True
_ANCHOR_OBJECTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
