# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='repo.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nrepo.proto\"\x17\n\x04Repo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\tb\x06proto3')
)




_REPO = _descriptor.Descriptor(
  name='Repo',
  full_name='Repo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Repo.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=37,
)

DESCRIPTOR.message_types_by_name['Repo'] = _REPO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Repo = _reflection.GeneratedProtocolMessageType('Repo', (_message.Message,), dict(
  DESCRIPTOR = _REPO,
  __module__ = 'repo_pb2'
  # @@protoc_insertion_point(class_scope:Repo)
  ))
_sym_db.RegisterMessage(Repo)


# @@protoc_insertion_point(module_scope)
